{% set name = "datefudge" %}
{% set version = "1.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://deb.debian.org/debian/pool/main/d/datefudge/datefudge_{{ version }}.tar.xz
  sha256: 80efab249232deeb142bf8a0ec66f2cf596c45560e4fdd28f3b5bdd290ac0385
  patches:
    - makefile.patch

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - datefudge "2003-04-01 09:42" date

about:
  home: https://packages.qa.debian.org/d/datefudge.html
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: Fake the system date

extra:
  recipe-maintainers:
    - scopatz
    - xhochy
